<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <RootNamespace>PIGI_PT_Application</RootNamespace>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="MediatR" Version="14.1.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\PIGI-PT-Domain\PIGI-PT-Domain.csproj" />
    </ItemGroup>

</Project>
